// Generated by page-blueprinter

import { WorkflowHero } from '@/components/domain/industries/coffee/heroes/WorkflowHero'
import { FeatureBento } from '@/components/domain/product/features'
import { IntegrationGrid } from '@/components/domain/product/integration'
import { KPIShowcase } from '@/components/shared/data-display'
import { CallToAction } from '@/components/shared/layout'

export default function Page() {
  return (
    <>
      <WorkflowHero />

      <FeatureBento variant={"dashboard"} />

      <IntegrationGrid title={"Coffee POS & Ops Integrations"} subtitle={"Connect OpsFlow to your café stack—POS, delivery, accounting & more."} integrations={[]} />

      <KPIShowcase industry={"coffee"} variant={"outline"} energy={"balanced"} leadKey={"Compliance"} />

      <CallToAction industry={"coffee"} variant={"demo"} customTitle={"Ready to Master Your Morning Rush?"} customSubtitle={"Join leading coffee shops optimizing consistency and speed with OpsFlow"} imageSrc={null} />
    </>
  )
}
