// Generated by page-blueprinter

import { WorkflowHero } from '@/templates/shadcn-components/processed/heroes'
import { FeatureBento } from '@/templates/shadcn-components/processed/features'
import { IntegrationGrid } from '@/templates/shadcn-components/processed/integration'
import { KPIShowcase } from '@/templates/shadcn-components/processed/stats'
import { CallToAction } from '@/templates/shadcn-components/processed/ctas'

export default function Page() {
  return (
    <>
      <WorkflowHero industry={"cafe"} role={"manager"} variant={"default"} />

      <FeatureBento variant={"dashboard"} />

      <IntegrationGrid title={"Coffee POS & Ops Integrations"} subtitle={"Connect OpsFlow to your café stack—POS, delivery, accounting & more."} featuredIds={[2]} />

      <KPIShowcase industry={"coffee"} variant={"outline"} energy={"balanced"} leadKey={"Compliance"} />

      <CallToAction industry={"coffee"} variant={"demo"} customTitle={"Ready to Master Your Morning Rush?"} customSubtitle={"Join leading coffee shops optimizing consistency and speed with OpsFlow"} />
    </>
  )
}
