// Generated by page-blueprinter

import { WorkflowHero } from '@/components/domain/industries/restaurants/heroes/WorkflowHero'
import { FeatureBento } from '@/components/domain/product/features'
import { KPIShowcase, MetricsDashboard, TestimonialGrid } from '@/components/shared/data-display'
import { IntegrationGrid } from '@/components/domain/product/integration'
import { CallToAction } from '@/components/shared/layout'

export default function Page() {
  return (
    <>
      <WorkflowHero />

      <FeatureBento variant={"dashboard"} />

      <MetricsDashboard industry={"restaurants"} />

      <IntegrationGrid title={"Restaurant Tech Integrations"} subtitle={"Connect OpsFlow with POS, delivery, payroll, accounting and more."} integrations={[]} />

      <KPIShowcase industry={"restaurants"} variant={"outline"} energy={"balanced"} leadKey={"Compliance"} />

      <TestimonialGrid />

      <CallToAction industry={"restaurants"} variant={"demo"} customTitle={"Ready to Transform Your Restaurant Operations?"} customSubtitle={"Join thousands of restaurants streamlining operations with OpsFlow"} imageSrc={null} />
    </>
  )
}
