// Generated by page-blueprinter

import { WorkflowHero } from '@/templates/shadcn-components/processed/heroes'
import { FeatureBento } from '@/templates/shadcn-components/processed/features'
import { KPIShowcase, MetricsDashboard } from '@/templates/shadcn-components/processed/stats'
import { IntegrationGrid } from '@/templates/shadcn-components/processed/integration'
import { TestimonialGrid } from '@/templates/shadcn-components/processed/testimonials'
import { CallToAction } from '@/templates/shadcn-components/processed/ctas'

export default function Page() {
  return (
    <>
      <WorkflowHero industry={"restaurant"} role={"manager"} variant={"default"} />

      <FeatureBento variant={"dashboard"} />

      <MetricsDashboard industry={"restaurants"} />

      <IntegrationGrid title={"Restaurant Tech Integrations"} subtitle={"Connect OpsFlow with POS, delivery, payroll, accounting and more."} featuredIds={[2]} />

      <KPIShowcase industry={"restaurants"} variant={"outline"} energy={"balanced"} leadKey={"Compliance"} />

      <TestimonialGrid />

      <CallToAction industry={"restaurants"} variant={"demo"} customTitle={"Ready to Transform Your Restaurant Operations?"} customSubtitle={"Join thousands of restaurants streamlining operations with OpsFlow"} />
    </>
  )
}
